#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d   󰈹   IV V VI VII VIII IX X

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config normal_border_color  "#54295c"
bspc config focused_border_color "#7fff00"



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom &
/home/nathan/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
#/home/nathan/.config/bspwm/wallpaper.sh &
feh --bg-scale /home/nathan/Imágenes/cyberpunk.png
#xrandr --output HDMI-1 --left-of eDP-1
#feh --bg-scale ~/Imágenes/space.png &
